# Generated by Django 6.0.5 on 2026-05-30 14:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('referral_code_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=16, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_code', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('referral_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('rewarded', 'Rewarded'), ('converted', 'Converted')], default='pending', max_length=20)),
                ('rewarded_at', models.DateTimeField(blank=True, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_record', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
                ('code_used', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='referral.referralcode')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralTransactions',
            fields=[
                ('transaction_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], default='PENDING', max_length=50)),
                ('reference_key', models.CharField(max_length=255, unique=True)),
                ('idempotency_key', models.UUIDField()),
                ('transfer_code', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('referrals', models.ManyToManyField(related_name='referrals', to='referral.referral')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral_transaction',
            },
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referrer', 'status'], name='referral_re_referre_00450c_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referred'], name='referral_re_referre_e7e551_idx'),
        ),
        migrations.AddIndex(
            model_name='referraltransactions',
            index=models.Index(fields=['status'], name='referral_re_status_0c031d_idx'),
        ),
        migrations.AddIndex(
            model_name='referraltransactions',
            index=models.Index(fields=['reference_key'], name='referral_re_referen_9be86d_idx'),
        ),
        migrations.AddIndex(
            model_name='referraltransactions',
            index=models.Index(fields=['idempotency_key'], name='referral_re_idempot_31d74e_idx'),
        ),
        migrations.AddIndex(
            model_name='referraltransactions',
            index=models.Index(fields=['created_at'], name='referral_re_created_218962_idx'),
        ),
        migrations.AddIndex(
            model_name='referraltransactions',
            index=models.Index(fields=['is_active'], name='referral_re_is_acti_fb8367_idx'),
        ),
    ]
