# Generated by Django 6.0.2 on 2026-04-24 00:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralTransactions',
            fields=[
                ('transaction_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], default='PENDING', max_length=50)),
                ('reference_key', models.CharField(max_length=255, unique=True)),
                ('idempotency_key', models.UUIDField()),
                ('transfer_code', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('referrals', models.ManyToManyField(related_name='referrals', to='referral.referral')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral_transaction',
                'indexes': [models.Index(fields=['status'], name='referral_re_status_0c031d_idx'), models.Index(fields=['reference_key'], name='referral_re_referen_9be86d_idx'), models.Index(fields=['idempotency_key'], name='referral_re_idempot_31d74e_idx'), models.Index(fields=['created_at'], name='referral_re_created_218962_idx'), models.Index(fields=['is_active'], name='referral_re_is_acti_fb8367_idx')],
            },
        ),
    ]
