# Generated by Django 6.0.5 on 2026-05-30 14:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('booking_id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('booking_status', models.CharField(choices=[('Pending', 'Pending'), ('Funded', 'Funded'), ('In_progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('is_remote', models.BooleanField(default=False)),
                ('currency', models.CharField(default='NGN', max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('descriptions', models.TextField()),
                ('requirements', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_accepted', to=settings.AUTH_USER_MODEL)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_address', to='users.useraddress')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_cancelled', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='users.providermodel')),
            ],
            options={
                'verbose_name': 'Booking',
            },
        ),
        migrations.CreateModel(
            name='BookingTransaction',
            fields=[
                ('transaction_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('type', models.CharField(choices=[('ESCROW_HOLD', 'Escrow Hold'), ('RELEASE', 'Release'), ('REFUND', 'Refund')], default='ESCROW_HOLD', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('idempotency_key', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_transactions', to='bookings.bookings')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PaymentTransactions',
            },
        ),
        migrations.CreateModel(
            name='PaymentRequestBooking',
            fields=[
                ('request_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('message', models.TextField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time')], default=None, max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_request', to='bookings.bookings')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_request_customer', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_request', to='users.providermodel')),
            ],
        ),
        migrations.CreateModel(
            name='BookingAttachments',
            fields=[
                ('attachment_id_booking', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('attachment_type_booking', models.CharField(blank=True, choices=[('VIDEO', 'Video'), ('PHOTO', 'Photo'), ('FILE', 'File')], default=None, max_length=200, null=True)),
                ('attachmentURL_booking', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='bookings.bookings')),
                ('payment_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments_payment_request', to='bookings.paymentrequestbooking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bookings',
            index=models.Index(fields=['is_active'], name='activ_de_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookings',
            constraint=models.UniqueConstraint(fields=('provider', 'start_date', 'end_date'), name='unique_booking_constraint'),
        ),
        migrations.AddIndex(
            model_name='bookingtransaction',
            index=models.Index(fields=['amount'], name='bookings_bo_amount_a5b5ea_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingtransaction',
            index=models.Index(fields=['status'], name='bookings_bo_status_180e4f_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingtransaction',
            index=models.Index(fields=['type'], name='bookings_bo_type_242156_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingtransaction',
            index=models.Index(fields=['idempotency_key'], name='bookings_bo_idempot_5f1375_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrequestbooking',
            index=models.Index(fields=['status'], name='bookings_pa_status_25c3b9_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrequestbooking',
            index=models.Index(fields=['requested_at'], name='bookings_pa_request_d68878_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrequestbooking',
            index=models.Index(fields=['message'], name='bookings_pa_message_abf533_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingattachments',
            index=models.Index(fields=['attachmentURL_booking'], name='media_idx'),
        ),
    ]
