# Generated by Django 6.0.5 on 2026-07-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
