# Generated by Django 6.0.2 on 2026-03-26 20:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('users', '0003_alter_providerskill_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingattachments',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='bookings.bookings'),
        ),
        migrations.CreateModel(
            name='PaymentRequestBooking',
            fields=[
                ('request_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('message', models.TextField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time')], default=None, max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_request', to='bookings.bookings')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_request_customer', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_request', to='users.providermodel')),
            ],
        ),
        migrations.AddField(
            model_name='bookingattachments',
            name='payment_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments_payment_request', to='bookings.paymentrequestbooking'),
        ),
        migrations.AddIndex(
            model_name='paymentrequestbooking',
            index=models.Index(fields=['status'], name='bookings_pa_status_25c3b9_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrequestbooking',
            index=models.Index(fields=['requested_at'], name='bookings_pa_request_d68878_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrequestbooking',
            index=models.Index(fields=['message'], name='bookings_pa_message_abf533_idx'),
        ),
    ]
