# Generated by Django 5.2.8 on 2026-02-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='payment_remark',
            field=models.TextField(blank=True),
        ),
    ]
