# Generated by Django 6.0.2 on 2026-04-04 07:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_bookingattachments_booking_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='paymentrequestbooking',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_request', to='bookings.bookings'),
        ),
        migrations.CreateModel(
            name='BookingTransaction',
            fields=[
                ('transaction_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('type', models.CharField(choices=[('ESCROW_HOLD', 'Escrow Hold'), ('RELEASE', 'Release'), ('REFUND', 'Refund')], default='ESCROW_HOLD', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('idempotency_key', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_transactions', to='bookings.bookings')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PaymentTransactions',
                'indexes': [models.Index(fields=['amount'], name='bookings_bo_amount_a5b5ea_idx'), models.Index(fields=['status'], name='bookings_bo_status_180e4f_idx'), models.Index(fields=['type'], name='bookings_bo_type_242156_idx'), models.Index(fields=['idempotency_key'], name='bookings_bo_idempot_5f1375_idx')],
            },
        ),
    ]
