# Generated by Django 6.0.5 on 2026-07-30 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_bookings_location'),
        ('users', '0013_alter_useraddress_postal_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bookingtransaction',
            name='bookings_bo_idempot_5f1375_idx',
        ),
        migrations.RenameField(
            model_name='bookingtransaction',
            old_name='idempotency_key',
            new_name='reference',
        ),
        migrations.AddField(
            model_name='bookings',
            name='is_urgent',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='provider_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='users.service'),
        ),
        migrations.AddIndex(
            model_name='bookingtransaction',
            index=models.Index(fields=['reference'], name='bookings_bo_referen_c574e2_idx'),
        ),
    ]
