# Generated by Django 5.2.8 on 2026-01-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_bookings_address_alter_bookings_cancelled_by'),
        ('users', '0002_service_serviceimage_alter_customermodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='service',
            field=models.ManyToManyField(blank=True, null=True, to='users.service'),
        ),
    ]
