# Generated by Django 5.2.8 on 2026-01-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_bookings_service'),
        ('users', '0003_address_unique_name_postal_code_constraints_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='booking_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='service',
            field=models.ManyToManyField(blank=True, to='users.service'),
        ),
    ]
