# Generated by Django 6.0.5 on 2026-07-30 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_bookingtransaction_bookings_bo_idempot_5f1375_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bookings',
            name='unique_booking_constraint',
        ),
    ]
