# Generated by Django 6.0.2 on 2026-05-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_bookings_platform_fee_alter_bookings_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='is_remote',
            field=models.BooleanField(default=False),
        ),
    ]
