# Generated by Django 6.0.5 on 2026-08-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_bookings_unique_booking_constraint'),
        ('users', '0013_alter_useraddress_postal_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='provider_service',
        ),
        migrations.AddField(
            model_name='bookings',
            name='provider_service',
            field=models.ManyToManyField(blank=True, null=True, related_name='bookings', to='users.service'),
        ),
    ]
