# Generated by Django 6.0.5 on 2026-08-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_remove_bookings_provider_service_and_more'),
        ('users', '0014_remove_service_category_remove_service_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='provider_service',
            field=models.ManyToManyField(blank=True, related_name='bookings', to='users.service'),
        ),
    ]
