# Generated by Django 6.0.5 on 2026-08-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_bookings_provider_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='descriptions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
