services:

  redis:
    image: redis:7-alpine
    restart: always
    expose: 
      - "6379"

  db_migrate:
    build: .
    container_name: db-migrate
    env_file:
      - .env
    command: ["uv", 'run', "backend/manage.py", "migrate", "--noinput"]

  collect_static:
    build: .
    container_name: static-files
    environment:
      - STATIC_ROOT=/vol/static
    volumes: 
      - static_volume:/vol/static
    env_file:
      - .env
    command: ["uv", 'run', "backend/manage.py", "collectstatic", "--noinput"]

  web:
    container_name: skills4Hire
    depends_on:
      db_migrate:
        condition: service_completed_successfully
    build: .
    command: [
      "uv", "run", "gunicorn", "-k", "daphne.gunicorn.workers.DaphneProcessWorker", "-b", 
      "0.0.0.0:8000", "config.asgi:application"
    ]
    env_file:
      - .env
    
    environment:
      - STATIC_ROOT=/vol/static
    volumes:
      - static_volume:/vol/static
    restart: "always"
    expose: 
      - "8000"

  celery-worker:
    build: .
    container_name: celery-worker
    command: ["uv", "run", "celery", "-A", "config", "worker", "--loglevel=info"]
    env_file:
      - .env
    restart: "unless-stopped"

  celery-beat:
    build: .
    container_name: celery-beat
    restart: "unless-stopped"
    env_file:
      - .env
    command: ["uv", "run", "celery", "-A", "config", "beat", "--loglevel=info"]

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx_server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - static_volume:/vol/static
    depends_on:
      - web
    restart: unless-stopped

  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/certbot
  #   entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done"

volumes:
  static_volume:
