services:
  db_migrate:
    build: .
    container_name: db-migrate
    env_file:
      - .env
    command: ["python3", "manage.py", "migrate", "--noinput"]

  collect_static:
    build: .
    container_name: static-files
    env_file:
      - .env
    command: ["python3", "manage.py", "collectstatic", "--noinout"]

  web:
    container_name: skills4Hire
    depends_on:
      db_migrate:
        condition: service_completed_successfully
    build: .
    command: ['sh', "build.sh"]
    env_file:
      - .env
    volumes:
      - .:/app
    restart: "always"
    ports:
      - "8000:8000"

  celery-worker:
    build: .
    volumes:
      - .:/app
    container_name: celery-worker
    command: ["celery", "-A", "config", "worker", "--loglevel=info"]
    env_file:
      - .env
    restart: "unless-stopped"

  celery-beat:
    build: .
    container_name: celery-beat
    restart: "unless-stopped"
    env_file:
      - .env
    command: ["celery", "-A", "config", "beat", "--loglevel=info"]
    volumes:
      - .:/app

