[pytest]

DJANGO_SETTINGS_MODULE = tests.settings
python_files = 
    tests.py 
    test_*.py 
    *_test.py 
    test.py
    *est.py 
    t*.py
    
pythonpath = .
testpaths = ./tests

markers = 
    api
    unit

addopts = 
    --reuse-db
    --strict-markers
    --tb=short
    -p no:warnings
    -s