# Generated by Django 6.0.2 on 2026-03-20 08:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileRating',
            fields=[
                ('rating_id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='users.customermodel')),
                ('provider_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='users.providermodel')),
                ('rate_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
                'db_table': 'ratings_ratings',
                'indexes': [models.Index(fields=['is_active'], name='ra_act_idx'), models.Index(fields=['created_at'], name='dat_idx'), models.Index(fields=['rate_by'], name='rated_by_idx')],
                'constraints': [models.UniqueConstraint(fields=('rate_by', 'customer_profile'), name='rate_profile_unique_customer'), models.UniqueConstraint(fields=('rate_by', 'provider_profile'), name='rate_profile_unique_provider')],
            },
        ),
        migrations.CreateModel(
            name='ProfileReview',
            fields=[
                ('review_id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('review', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.customermodel')),
                ('provider_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.providermodel')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'db_table': 'ratings_review',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active'], name='active_deleted_idx'), models.Index(fields=['created_at'], name='d_idx')],
                'constraints': [models.UniqueConstraint(fields=('reviewed_by', 'customer_profile'), name='unique_review_profile_customer'), models.UniqueConstraint(fields=('reviewed_by', 'provider_profile'), name='unique_user_profile')],
            },
        ),
    ]
