# Generated by Django 6.0.2 on 2026-04-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='profilereview',
            name='unique_review_profile_customer',
        ),
        migrations.AlterField(
            model_name='profilereview',
            name='review',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.RemoveField(
            model_name='profilereview',
            name='customer_profile',
        ),
    ]
