# Generated by Django 5.2.8 on 2026-02-20 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
        ('users', '0002_remove_serviceimage_service_serviceimage_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilerating',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='users.providermodel'),
        ),
        migrations.AlterField(
            model_name='profilereview',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.providermodel'),
        ),
    ]
