# Generated by Django 6.0.2 on 2026-04-17 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_remove_profilereview_unique_review_profile_customer_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='profilerating',
            name='rate_profile_unique_customer',
        ),
        migrations.RemoveField(
            model_name='profilerating',
            name='customer_profile',
        ),
    ]
