# Generated by Django 6.0.2 on 2026-04-24 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_remove_profilerating_rate_profile_unique_customer_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='profilerating',
            name='ra_act_idx',
        ),
        migrations.RemoveIndex(
            model_name='profilerating',
            name='dat_idx',
        ),
        migrations.RemoveIndex(
            model_name='profilerating',
            name='rated_by_idx',
        ),
        migrations.RemoveConstraint(
            model_name='profilerating',
            name='rate_profile_unique_provider',
        ),
        migrations.RemoveField(
            model_name='profilereview',
            name='review',
        ),
        migrations.AddField(
            model_name='profilereview',
            name='ratings',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='profilereview',
            name='reviews',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name='ProfileRating',
        ),
    ]
