# Generated by Django 6.0.2 on 2026-03-03 11:43

import autoslug.fields
import django.db.models.deletion
import django_countries.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseProfile',
            fields=[
                ('profile_id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], db_index=True, max_length=100)),
                ('bio', models.TextField(blank=True, max_length=10000, null=True)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('location', models.CharField(max_length=225)),
                ('is_verified', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Avater',
            fields=[
                ('avater_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('avater', models.URLField(blank=True, null=True)),
                ('avater_public_id', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avater', to='users.baseprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('line1', models.CharField(max_length=200)),
                ('line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='users.baseprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('skill_category_id', models.UUIDField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('DIGITAL', 'Digital'), ('VOCATIONAL', 'Vocational'), ('CRAFT', 'Craft')], default='DIGITAL', max_length=200, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='category', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'category'), name='unique_name_category')],
            },
        ),
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('customer_id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('website', models.URLField(blank=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('industry', models.URLField(blank=True, null=True)),
                ('total_hires', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to='users.baseprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderModel',
            fields=[
                ('provider_id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('occupation', models.CharField(blank=True, max_length=250, null=True)),
                ('headline', models.CharField(blank=True, max_length=255)),
                ('overview', models.TextField(blank=True)),
                ('experience_level', models.CharField(choices=[('JUNIOR', 'Junior'), ('MID', 'Mid'), ('SENIOR', 'Senior'), ('EXPERTExpert', 'Expert')], default='JUNIOR', max_length=20)),
                ('availability', models.CharField(choices=[('FULL_TIME', 'Full_time'), ('PART_TIME', 'Part_time'), ('HYBRID', 'Hybrid'), ('CONTRCT', 'Contract')], default='FULL_TIME', max_length=20)),
                ('min_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hourly_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('features', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('jobs_done', models.PositiveIntegerField(default=0)),
                ('about', models.TextField()),
                ('max_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('favourite', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to='users.baseprofile')),
            ],
            options={
                'verbose_name_plural': 'provider_models',
            },
        ),
        migrations.CreateModel(
            name='ProviderSkills',
            fields=[
                ('skill_id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('efficiency', models.CharField(choices=[('BEGINEER', 'Begineer'), ('INTERMIDIATE', 'Intermidiate'), ('EXPERT', 'Expert')], default='BEGINEER', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('level_of_experience', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('work', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='skills', to='users.category')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='users.providermodel')),
            ],
            options={
                'verbose_name': 'provider_skills',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True)),
                ('min_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='users.providermodel')),
            ],
            options={
                'verbose_name': 'services',
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('image_id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('image_public_id', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ManyToManyField(related_name='images', to='users.service')),
            ],
        ),
        migrations.AddIndex(
            model_name='baseprofile',
            index=models.Index(fields=['is_active', 'is_deleted'], name='is_d_idx'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(fields=('profile', 'postal_code'), name='unique_name_postal_code_constraints'),
        ),
        migrations.AddIndex(
            model_name='customermodel',
            index=models.Index(fields=['is_active', 'is_deleted'], name='dele_acti_idx'),
        ),
        migrations.AddIndex(
            model_name='customermodel',
            index=models.Index(fields=['is_active', 'is_deleted', 'is_verified'], name='very_dele_acti_idx'),
        ),
        migrations.AddIndex(
            model_name='providermodel',
            index=models.Index(fields=['availability'], name='availability_idx'),
        ),
        migrations.AddIndex(
            model_name='providermodel',
            index=models.Index(fields=['is_active', 'is_deleted'], name='act_del_idx'),
        ),
        migrations.AddIndex(
            model_name='providerskills',
            index=models.Index(fields=['is_active', 'is_deleted'], name='ac_dele_idx'),
        ),
        migrations.AddConstraint(
            model_name='providerskills',
            constraint=models.UniqueConstraint(fields=('profile', 'category'), name='profile_name_contraints'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_active', 'is_deleted'], name='srv_act_del_idx'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('name', 'profile'), name='unique_service_constraints'),
        ),
    ]
