# Generated by Django 6.0.2 on 2026-03-20 08:01

import django.db.models.deletion
import django.db.models.manager
import django_countries.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['sort_order', 'name'],
            },
            managers=[
                ('active_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='BaseProfile',
            fields=[
                ('profile_id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], db_index=True, max_length=100)),
                ('bio', models.TextField(blank=True, max_length=10000, null=True)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('avatar_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('avatar_public_id', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to='users.baseprofile')),
            ],
            options={
                'verbose_name': 'Profile Avatar',
                'verbose_name_plural': 'Profile Avatars',
            },
        ),
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('customer_id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('city', models.CharField(blank=True, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('industry_name', models.CharField(blank=True, db_index=True, null=True)),
                ('total_hires', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to='users.baseprofile')),
            ],
            options={
                'verbose_name': 'Customer Profile',
                'verbose_name_plural': 'Customer Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderModel',
            fields=[
                ('provider_id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('professional_title', models.CharField(max_length=250, null=True)),
                ('headline', models.CharField(blank=True, max_length=255)),
                ('overview', models.TextField(blank=True)),
                ('experience_level', models.CharField(choices=[('entry', 'Entry Level'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], default='entry', max_length=20)),
                ('availability', models.CharField(choices=[('available', 'Available'), ('partially', 'Partially Available'), ('unavailable', 'Not Available')], default='partially', max_length=20)),
                ('min_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hourly_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('years_of_experience', models.PositiveSmallIntegerField(default=0)),
                ('open_to_full_time', models.BooleanField(default=False, help_text='Willing to convert to full-time employment.')),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('description', models.TextField(blank=True)),
                ('jobs_done', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('is_top_rated', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to='users.baseprofile')),
            ],
            options={
                'verbose_name': 'Professional Profile',
                'verbose_name_plural': 'Professional Profiles',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('min_charge', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('max_charge', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='users.providermodel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceAttachment',
            fields=[
                ('image_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image_url', models.URLField(max_length=2048)),
                ('image_public_id', models.CharField(max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='users.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to='users.category')),
            ],
            options={
                'ordering': ['name'],
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ProviderSkill',
            fields=[
                ('provider_skill_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('proficiency', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20)),
                ('years_used', models.PositiveSmallIntegerField(default=0)),
                ('is_primary', models.BooleanField(db_index=True, default=False, help_text='Primary skills are highlighted at the top of the profile.')),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level_of_experience', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('provider_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='users.providermodel')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_skills', to='users.skill')),
            ],
            options={
                'ordering': ['-is_primary', 'sort_order'],
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('address_id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('street_address', models.CharField(max_length=255)),
                ('apartment', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='users.baseprofile')),
            ],
            options={
                'verbose_name_plural': 'User Addresses',
            },
        ),
        migrations.AddIndex(
            model_name='baseprofile',
            index=models.Index(fields=['is_active'], name='is_d_idx'),
        ),
        migrations.AddIndex(
            model_name='avatar',
            index=models.Index(fields=['profile'], name='users_avata_profile_94907d_idx'),
        ),
        migrations.AddIndex(
            model_name='avatar',
            index=models.Index(fields=['avatar'], name='users_avata_avatar_dd6189_idx'),
        ),
        migrations.AddIndex(
            model_name='avatar',
            index=models.Index(fields=['is_active'], name='users_avata_is_acti_b9a364_idx'),
        ),
        migrations.AddIndex(
            model_name='customermodel',
            index=models.Index(fields=['is_active'], name='dele_acti_idx'),
        ),
        migrations.AddIndex(
            model_name='customermodel',
            index=models.Index(fields=['is_active', 'is_verified'], name='very_dele_acti_idx'),
        ),
        migrations.AddIndex(
            model_name='providermodel',
            index=models.Index(fields=['availability'], name='users_provi_availab_a4b044_idx'),
        ),
        migrations.AddIndex(
            model_name='providermodel',
            index=models.Index(fields=['hourly_pay'], name='users_provi_hourly__f76a72_idx'),
        ),
        migrations.AddIndex(
            model_name='providermodel',
            index=models.Index(fields=['jobs_done'], name='users_provi_jobs_do_944988_idx'),
        ),
        migrations.AddIndex(
            model_name='providermodel',
            index=models.Index(fields=['min_charge'], name='users_provi_min_cha_b0ada2_idx'),
        ),
        migrations.AddIndex(
            model_name='providermodel',
            index=models.Index(fields=['max_charge'], name='users_provi_max_cha_b29a7e_idx'),
        ),
        migrations.AddIndex(
            model_name='providermodel',
            index=models.Index(fields=['experience_level'], name='users_provi_experie_7a5dbe_idx'),
        ),
        migrations.AddIndex(
            model_name='providermodel',
            index=models.Index(fields=['is_top_rated', 'is_featured'], name='users_provi_is_top__7409b8_idx'),
        ),
        migrations.AddIndex(
            model_name='providermodel',
            index=models.Index(fields=['professional_title'], name='users_provi_profess_94a433_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['profile', 'is_active'], name='users_servi_profile_3250f3_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['deleted_at'], name='users_servi_deleted_dc7308_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_active'], name='users_servi_is_acti_7747b2_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceattachment',
            index=models.Index(fields=['service', 'is_active'], name='users_servi_service_a3b14f_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['name'], name='users_skill_name_0b8e75_idx'),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='unique_category_name'),
        ),
        migrations.AddIndex(
            model_name='providerskill',
            index=models.Index(fields=['skill', 'proficiency'], name='users_provi_skill_i_a67261_idx'),
        ),
        migrations.AddConstraint(
            model_name='providerskill',
            constraint=models.UniqueConstraint(fields=('provider_profile', 'skill'), name='unique_provider_skill'),
        ),
        migrations.AddConstraint(
            model_name='useraddress',
            constraint=models.UniqueConstraint(fields=('postal_code', 'user_profile'), name='unique_postal_code'),
        ),
    ]
