# Generated by Django 5.2.8 on 2026-02-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceimage',
            name='service',
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='service',
            field=models.ManyToManyField(related_name='images', to='users.service'),
        ),
    ]
