# Generated by Django 5.2.8 on 2025-12-27 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_baseprofile_gender_alter_providermodel_profile'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='providermodel',
            name='avaialbiloity_idx',
        ),
        migrations.RemoveField(
            model_name='providermodel',
            name='avialability',
        ),
        migrations.AddField(
            model_name='providermodel',
            name='availability',
            field=models.CharField(choices=[('FULL_TIME', 'Full_time'), ('PART_TIME', 'Part_time'), ('HYBRID', 'Hybrid'), ('CONTRCT', 'Contract')], default='FULL_TIME', max_length=20),
        ),
        migrations.AlterField(
            model_name='providermodel',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to='users.baseprofile'),
        ),
        migrations.AddIndex(
            model_name='providermodel',
            index=models.Index(fields=['availability'], name='availability_idx'),
        ),
    ]
