# Generated by Django 6.0.2 on 2026-03-26 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customermodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='providerskill',
            options={'ordering': ['-is_primary', 'sort_order']},
        ),
    ]
