# Generated by Django 5.2.8 on 2026-01-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_address_created_at_address_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerskills',
            name='work_refrences',
            field=models.TextField(blank=True, null=True),
        ),
    ]
