# Generated by Django 5.2.8 on 2026-02-20 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_serviceimage_service_serviceimage_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providermodel',
            name='is_online',
        ),
    ]
