# Generated by Django 6.0.5 on 2026-06-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_providermodel_max_charge_providermodel_min_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
