# Generated by Django 5.2.8 on 2026-01-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_service_serviceimage_alter_customermodel_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(fields=('profile', 'postal_code'), name='unique_name_postal_code_constraints'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('name', 'profile'), name='unique_service_constraints'),
        ),
    ]
