# Generated by Django 5.2.8 on 2026-01-05 10:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_providermodel_avaialbiloity_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providermodel',
            name='id',
        ),
        migrations.AddField(
            model_name='providermodel',
            name='provider_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('client_id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('organisation_name', models.CharField(blank=True, max_length=200)),
                ('organisation_type', models.CharField(blank=True, max_length=200)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('total_hires', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to='users.baseprofile')),
            ],
        ),
    ]
