# Generated by Django 6.0.5 on 2026-06-17 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_baseprofile_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermodel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customermodel',
            name='country',
        ),
    ]
