# Generated by Django 5.2.8 on 2026-01-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_providermodel_id_providermodel_provider_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providermodel',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='providermodel',
            name='features',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='providermodel',
            name='headline',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='providermodel',
            name='hourly_pay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='providermodel',
            name='max_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='providermodel',
            name='min_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='providermodel',
            name='occupation',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='providermodel',
            name='overview',
            field=models.TextField(blank=True),
        ),
    ]
