# Generated by Django 6.0.5 on 2026-06-28 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customermodel_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='max_charge',
        ),
        migrations.RemoveField(
            model_name='service',
            name='min_charge',
        ),
        migrations.AddField(
            model_name='service',
            name='charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='years_of_experience',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
