# Generated by Django 6.0.5 on 2026-06-28 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_service_max_charge_remove_service_min_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workimages',
            name='image_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='workimages',
            name='public_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
