# Generated by Django 5.2.8 on 2026-01-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_providermodel_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avater',
            name='avater_public_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='avater',
            name='avater',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avater',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
