# Generated by Django 6.0.2 on 2026-04-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_favourite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'skill categories'},
        ),
        migrations.AlterModelOptions(
            name='providerskill',
            options={},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name_plural': 'skills'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='category',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='providerskill',
            name='level_of_experience',
        ),
        migrations.RemoveField(
            model_name='providerskill',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='is_featured',
        ),
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='providerskill',
            name='years_used',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
