# Generated by Django 5.2.8 on 2026-01-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_avater_avater_public_id_alter_avater_avater_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avater',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
