# Generated by Django 6.0.5 on 2026-06-29 00:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_workimages_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workimages',
            name='id',
        ),
        migrations.AddField(
            model_name='workimages',
            name='work_image_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
