# Generated by Django 6.0.5 on 2026-07-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_workimages_id_workimages_work_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceattachment',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='serviceattachment',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
