# Generated by Django 6.0.2 on 2026-05-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_category_options_alter_providerskill_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='serviceattachment',
            name='users_servi_service_a3b14f_idx',
        ),
        migrations.AddIndex(
            model_name='serviceattachment',
            index=models.Index(fields=['service'], name='users_servi_service_28ba2f_idx'),
        ),
        migrations.RemoveField(
            model_name='serviceattachment',
            name='is_active',
        ),
    ]
