# Generated by Django 6.0.5 on 2026-07-03 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_serviceattachment_thumbnail_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceattachment',
            old_name='thumbnail_url',
            new_name='thumnail_url',
        ),
    ]
