# Generated by Django 6.0.5 on 2026-07-03 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_thumbnail_url_serviceattachment_thumnail_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceattachment',
            old_name='thumnail_url',
            new_name='thumbnail_url',
        ),
    ]
