# Generated by Django 6.0.5 on 2026-07-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_thumnail_url_serviceattachment_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='workimages',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workimages',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
