# Generated by Django 6.0.2 on 2026-05-12 10:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_useraddress_postal_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='baseprofile',
            name='category_interest',
            field=models.JSONField(blank=True, default=list, help_text='Categories the user engages with for recommendations'),
        ),
        migrations.AddField(
            model_name='baseprofile',
            name='is_active_user',
            field=models.BooleanField(db_index=True, default=True, help_text='User is actively engaging with the platform'),
        ),
        migrations.AddField(
            model_name='baseprofile',
            name='last_active',
            field=models.DateTimeField(blank=True, help_text='Last time user logged in or interacted with content', null=True),
        ),
        migrations.AddField(
            model_name='baseprofile',
            name='location',
            field=models.CharField(blank=True, help_text="User's primary location for relevance scoring", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='baseprofile',
            name='trust_score',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddIndex(
            model_name='baseprofile',
            index=models.Index(fields=['trust_score'], name='trust_score_idx'),
        ),
        migrations.AddIndex(
            model_name='baseprofile',
            index=models.Index(fields=['is_active_user'], name='is_active_user_idx'),
        ),
        migrations.AddIndex(
            model_name='baseprofile',
            index=models.Index(fields=['last_active'], name='last_active_idx'),
        ),
    ]
