# Generated by Django 6.0.2 on 2026-05-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_baseprofile_category_interest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='years_of_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='providermodel',
            name='availability',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('PARTIALLY', 'Partially'), ('UNAVAILABLE', 'Unavailable')], default='PARTIALLY', max_length=20),
        ),
        migrations.AlterField(
            model_name='providermodel',
            name='experience_level',
            field=models.CharField(choices=[('ENTRY', 'Entry'), ('INTERMEDIATE', 'Intermediate'), ('EXPERT', 'Expert')], default='ENTRY', max_length=20),
        ),
    ]
