# Generated by Django 6.0.5 on 2026-07-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_workimages_thumbnail_url_workimages_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workimages',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
