# Generated by Django 6.0.2 on 2026-05-16 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_service_years_of_experience_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='baseprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baseprofile',
            name='drivers_license_photo_url',
            field=models.URLField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='baseprofile',
            name='is_certified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='baseprofile',
            name='nin',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='baseprofile',
            name='passport_photo_url',
            field=models.URLField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='baseprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='baseprofile',
            name='place_of_work',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='baseprofile',
            name='public_id_drivers_license_photo_url',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='baseprofile',
            name='public_id_passport_photo_url',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='baseprofile',
            name='years_of_experience',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseprofile',
            name='category_interest',
            field=models.ForeignKey(blank=True, help_text="User's primary service category interest for relevance scoring", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interested_profiles', to='users.servicecategory'),
        ),
        migrations.AlterField(
            model_name='providerskill',
            name='proficiency',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('EXPERT', 'Expert')], default='INTERMEDIATE', max_length=20),
        ),
        migrations.AddIndex(
            model_name='baseprofile',
            index=models.Index(fields=['is_certified'], name='is_certified_idx'),
        ),
        migrations.AddField(
            model_name='workimages',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_images', to='users.baseprofile'),
        ),
    ]
