# Generated by Django 6.0.2 on 2026-05-17 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_workimages_baseprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseprofile',
            name='category_interest',
        ),
        migrations.AddField(
            model_name='baseprofile',
            name='category_interest',
            field=models.ManyToManyField(blank=True, help_text="User's primary service category interest for relevance scoring", null=True, related_name='interested_profiles', to='users.servicecategory'),
        ),
    ]
