# Generated by Django 6.0.5 on 2026-08-04 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_service_category_remove_service_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainservice',
            old_name='_id',
            new_name='id',
        ),
    ]
