# Generated by Django 6.0.2 on 2026-05-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_baseprofile_category_interest_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='providermodel',
            name='users_provi_hourly__f76a72_idx',
        ),
        migrations.RemoveIndex(
            model_name='providermodel',
            name='users_provi_jobs_do_944988_idx',
        ),
        migrations.RemoveIndex(
            model_name='providermodel',
            name='users_provi_min_cha_b0ada2_idx',
        ),
        migrations.RemoveIndex(
            model_name='providermodel',
            name='users_provi_max_cha_b29a7e_idx',
        ),
        migrations.RemoveIndex(
            model_name='providermodel',
            name='users_provi_experie_7a5dbe_idx',
        ),
        migrations.RemoveIndex(
            model_name='providermodel',
            name='users_provi_is_top__7409b8_idx',
        ),
        migrations.RemoveField(
            model_name='baseprofile',
            name='drivers_license_photo_url',
        ),
        migrations.RemoveField(
            model_name='baseprofile',
            name='passport_photo_url',
        ),
        migrations.RemoveField(
            model_name='baseprofile',
            name='public_id_drivers_license_photo_url',
        ),
        migrations.RemoveField(
            model_name='baseprofile',
            name='public_id_passport_photo_url',
        ),
        migrations.AddField(
            model_name='baseprofile',
            name='certificates',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='baseprofile',
            name='drivers_lisence',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='baseprofile',
            name='user-passport',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='baseprofile',
            name='category_interest',
            field=models.ManyToManyField(blank=True, help_text="User's primary service category interest for relevance scoring", related_name='interested_profiles', to='users.servicecategory'),
        ),
        migrations.RemoveField(
            model_name='providermodel',
            name='hourly_pay',
        ),
        migrations.RemoveField(
            model_name='providermodel',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='providermodel',
            name='is_top_rated',
        ),
        migrations.RemoveField(
            model_name='providermodel',
            name='jobs_done',
        ),
        migrations.RemoveField(
            model_name='providermodel',
            name='max_charge',
        ),
        migrations.RemoveField(
            model_name='providermodel',
            name='min_charge',
        ),
        migrations.RemoveField(
            model_name='providermodel',
            name='years_of_experience',
        ),
    ]
