# Generated by Django 6.0.5 on 2026-05-26 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_providermodel_users_provi_hourly__f76a72_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseprofile',
            old_name='user-passport',
            new_name='passport',
        ),
    ]
