# Generated by Django 6.0.5 on 2026-08-04 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_rename__id_mainservice_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainservice',
            old_name='id',
            new_name='main_servce_id',
        ),
    ]
