# Generated by Django 6.0.5 on 2026-08-04 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_rename_id_mainservice_main_servce_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainservice',
            old_name='main_servce_id',
            new_name='main_service_id',
        ),
    ]
