# Generated by Django 6.0.5 on 2026-08-06 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_service_description_service_features_service_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='useraddress',
            name='unique_postal_code',
        ),
    ]
