# Generated by Django 6.0.5 on 2026-08-06 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_useraddress_unique_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='features',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
