# Generated by Django 6.0.5 on 2026-08-07 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_service_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='is_default',
        ),
    ]
