# Generated by Django 6.0.2 on 2026-03-03 11:43

import autoslug.fields
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='username', unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=50, null=True, region=None)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('active_role', models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('CUSTOMER', 'Customer'), ('SERVICE_PROVIDER', 'Service_provider')], default=None, max_length=30, null=True)),
                ('is_provider', models.BooleanField(default=False)),
                ('is_customer', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('is_staff', models.BooleanField(db_index=True, default=False)),
                ('is_superuser', models.BooleanField(db_index=True, default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'users',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OneTimePassword',
            fields=[
                ('otp_id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('hash_code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('raw_code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_time_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OneTimePassword',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='email_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['phone'], name='phone_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['active_role'], name='active_role_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['first_name', 'last_name'], name='first_last_name_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_provider'], name='provider_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_customer'], name='customer_idx'),
        ),
        migrations.AddIndex(
            model_name='onetimepassword',
            index=models.Index(fields=['hash_code'], name='hash_cde_idx'),
        ),
        migrations.AddIndex(
            model_name='onetimepassword',
            index=models.Index(fields=['is_active', 'is_used'], name='active_used_idx'),
        ),
        migrations.AddConstraint(
            model_name='onetimepassword',
            constraint=models.UniqueConstraint(fields=('user', 'hash_code', 'raw_code'), name='unique_code_user'),
        ),
    ]
