# Generated by Django 5.2.8 on 2026-02-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='onetimepassword',
            name='unique_code_user',
        ),
        migrations.AddField(
            model_name='onetimepassword',
            name='raw_code',
            field=models.CharField(db_index=True, default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='onetimepassword',
            constraint=models.UniqueConstraint(fields=('user', 'hash_code', 'raw_code'), name='unique_code_user'),
        ),
    ]
