# Generated by Django 6.0.2 on 2026-03-08 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimepassword',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
