# Generated by Django 6.0.5 on 2026-06-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='login_provider',
            field=models.CharField(choices=[('SYSTEM', 'System'), ('GOOGLE', 'Google'), ('FACEBOOK', 'Facebook'), ('APPLE', 'Apple')], default='SYSTEM', max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=125, null=True),
        ),
    ]
