# Generated by Django 5.2.8 on 2025-12-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_otp_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp_base',
            name='code',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
