# Generated by Django 5.2.8 on 2026-01-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_otp_base_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CLIENT', 'Client'), ('SERVICE_PROVIDER', 'Service_provider')], default=None, max_length=30),
        ),
    ]
