# Generated by Django 5.2.8 on 2026-01-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0005_alter_customuser_role'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customuser',
            name='role_idx',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('CLIENT', 'Client'), ('SERVICE_PROVIDER', 'Service_provider')], default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_provider',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['active_role'], name='active_role_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_provider'], name='provider_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_client'], name='client_idx'),
        ),
    ]
