# Generated by Django 5.2.8 on 2026-01-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_customuser_role_idx_remove_customuser_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
