# Generated by Django 5.2.8 on 2026-01-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0008_alter_customuser_phone'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customuser',
            name='client_idx',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='is_client',
            new_name='is_customer',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='active_role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('CUSTOMER', 'Customer'), ('SERVICE_PROVIDER', 'Service_provider')], default=None, max_length=30, null=True),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_customer'], name='customer_idx'),
        ),
    ]
