# Generated by Django 6.0.5 on 2026-05-30 14:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('conversation_id', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='pk  for conversation', primary_key=True, serialize=False, unique=True)),
                ('room_type', models.CharField(choices=[('direct', 'Direct'), ('support', 'Support')], db_index=True, default='direct', help_text='Type of conversation room', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Status of this conversation')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Conversation creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last message timestamp (updates when new message added)')),
                ('participant_one', models.ForeignKey(help_text='First participant in the conversation', on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_participant_one', to=settings.AUTH_USER_MODEL)),
                ('participant_two', models.ForeignKey(help_text='Second participant in the conversation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_participant_two', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'db_table': 'conversations_conversation',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Endorsements',
            fields=[
                ('endorsement_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('reason', models.TextField(max_length=500)),
                ('extra_message', models.CharField(blank=True, max_length=255, null=True)),
                ('is_hidden', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('endorsed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endorsed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsed_by', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_endorse', to='users.providermodel')),
            ],
            options={
                'verbose_name': 'Endorsement',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('content', models.TextField(help_text='Message content', max_length=5000)),
                ('is_read', models.BooleanField(default=False, help_text='Whether message has been read by recipient')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Message creation timestamp')),
                ('is_active', models.BooleanField(default=True)),
                ('is_edited', models.BooleanField(default=False, help_text='Whether message has been edited')),
                ('edited_at', models.DateTimeField(blank=True, help_text='Timestamp of last edit', null=True)),
                ('conversation', models.ForeignKey(help_text='Conversation this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.conversation')),
                ('sender', models.ForeignKey(help_text='User who sent this message', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'conversations_message',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Negotiations',
            fields=[
                ('negotiation_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('COUNTERED', 'Countered'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PROPOSED', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_price', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=10, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('countered_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='negotiations', to='chats.conversation')),
                ('job_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='negotiations', to='posts.post')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'negotiation',
                'db_table': 'negotiationhistory',
            },
        ),
        migrations.CreateModel(
            name='NegotiationHistory',
            fields=[
                ('history_id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('action', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='negotiation_history', to=settings.AUTH_USER_MODEL)),
                ('negotiation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='histories', to='chats.negotiations')),
            ],
            options={
                'db_table': 'negotiation_history',
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['participant_one', 'participant_two'], name='conversatio_partici_2d7300_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['participant_two', 'participant_one'], name='conversatio_partici_f44a3c_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['created_at'], name='conversatio_created_5a5006_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['updated_at'], name='conversatio_updated_cd54d7_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['room_type'], name='conversation_room_type_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['participant_one', 'updated_at'], name='conversation_user_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['participant_two', 'updated_at'], name='conversation_user2_updated_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('participant_one', 'participant_two'), name='unique_conversation_participants'),
        ),
        migrations.AddIndex(
            model_name='endorsements',
            index=models.Index(fields=['endorsement_id'], name='chats_endor_endorse_6fb2ca_idx'),
        ),
        migrations.AddIndex(
            model_name='endorsements',
            index=models.Index(fields=['endorsed_at'], name='chats_endor_endorse_f8d5af_idx'),
        ),
        migrations.AddIndex(
            model_name='endorsements',
            index=models.Index(fields=['updated_at'], name='chats_endor_updated_71be18_idx'),
        ),
        migrations.AddIndex(
            model_name='endorsements',
            index=models.Index(fields=['reason'], name='chats_endor_reason_4820fb_idx'),
        ),
        migrations.AddConstraint(
            model_name='endorsements',
            constraint=models.UniqueConstraint(fields=('endorsed_by', 'provider'), name='unique_sender'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='conversatio_convers_4b968d_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'is_read'], name='conversatio_convers_c89e02_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender'], name='conversatio_sender__ed16aa_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['created_at'], name='conversatio_created_792fff_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'is_read', 'created_at'], name='message_conv_read_created_idx'),
        ),
        migrations.AddIndex(
            model_name='negotiations',
            index=models.Index(fields=['conversation'], name='conversation_idx'),
        ),
        migrations.AddIndex(
            model_name='negotiations',
            index=models.Index(fields=['job_post'], name='job_post_idx'),
        ),
        migrations.AddIndex(
            model_name='negotiations',
            index=models.Index(fields=['status'], name='nego_status_idx'),
        ),
        migrations.AddIndex(
            model_name='negotiations',
            index=models.Index(fields=['countered_at'], name='countered_at_idx'),
        ),
        migrations.AddIndex(
            model_name='negotiations',
            index=models.Index(fields=['accepted_at'], name='accepted_at_idx'),
        ),
        migrations.AddIndex(
            model_name='negotiations',
            index=models.Index(fields=['price'], name='price_idx'),
        ),
        migrations.AddIndex(
            model_name='negotiationhistory',
            index=models.Index(fields=['action'], name='action_idx'),
        ),
        migrations.AddIndex(
            model_name='negotiationhistory',
            index=models.Index(fields=['negotiation'], name='nego_idx'),
        ),
        migrations.AddIndex(
            model_name='negotiationhistory',
            index=models.Index(fields=['created_at'], name='idx_date'),
        ),
    ]
