# Generated by Django 6.0.5 on 2026-08-05 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='endorsements',
            name='unique_sender',
        ),
    ]
