# Generated by Django 6.0.2 on 2026-03-29 20:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
        ('users', '0003_alter_providerskill_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Endorsements',
            fields=[
                ('endorement_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('reason', models.TextField(max_length=500)),
                ('extra_message', models.CharField(blank=True, max_length=255, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('endorsed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endorsed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsed_by', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_endorse', to='users.providermodel')),
            ],
            options={
                'verbose_name': 'Endorsement',
                'indexes': [models.Index(fields=['endorement_id'], name='chats_endor_endorem_a45846_idx'), models.Index(fields=['endorsed_at'], name='chats_endor_endorse_f8d5af_idx'), models.Index(fields=['updated_at'], name='chats_endor_updated_71be18_idx'), models.Index(fields=['reason'], name='chats_endor_reason_4820fb_idx')],
                'constraints': [models.UniqueConstraint(fields=('endorsed_by', 'provider'), name='unique_sender')],
            },
        ),
    ]
