# Generated by Django 6.0.2 on 2026-05-09 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0001_initial'),
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiations',
            name='job_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='negotiations', to='posts.post'),
        ),
        migrations.AddField(
            model_name='negotiations',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='negotiationhistory',
            name='negotiation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='histories', to='chats.negotiations'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['participant_one', 'participant_two'], name='conversatio_partici_2d7300_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['participant_two', 'participant_one'], name='conversatio_partici_f44a3c_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['created_at'], name='conversatio_created_5a5006_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['updated_at'], name='conversatio_updated_cd54d7_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['participant_one', 'updated_at'], name='conversation_user_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['participant_two', 'updated_at'], name='conversation_user2_updated_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('participant_one', 'participant_two'), name='unique_conversation_participants'),
        ),
        migrations.AddIndex(
            model_name='endorsements',
            index=models.Index(fields=['endorsement_id'], name='chats_endor_endorse_6fb2ca_idx'),
        ),
        migrations.AddIndex(
            model_name='endorsements',
            index=models.Index(fields=['endorsed_at'], name='chats_endor_endorse_f8d5af_idx'),
        ),
        migrations.AddIndex(
            model_name='endorsements',
            index=models.Index(fields=['updated_at'], name='chats_endor_updated_71be18_idx'),
        ),
        migrations.AddIndex(
            model_name='endorsements',
            index=models.Index(fields=['reason'], name='chats_endor_reason_4820fb_idx'),
        ),
        migrations.AddConstraint(
            model_name='endorsements',
            constraint=models.UniqueConstraint(fields=('endorsed_by', 'provider'), name='unique_sender'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='conversatio_convers_4b968d_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'is_read'], name='conversatio_convers_c89e02_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender'], name='conversatio_sender__ed16aa_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['created_at'], name='conversatio_created_792fff_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'is_read', 'created_at'], name='message_conv_read_created_idx'),
        ),
        migrations.AddIndex(
            model_name='negotiations',
            index=models.Index(fields=['conversation'], name='conversation_idx'),
        ),
        migrations.AddIndex(
            model_name='negotiations',
            index=models.Index(fields=['job_post'], name='job_post_idx'),
        ),
        migrations.AddIndex(
            model_name='negotiations',
            index=models.Index(fields=['status'], name='nego_status_idx'),
        ),
        migrations.AddIndex(
            model_name='negotiations',
            index=models.Index(fields=['countered_at'], name='countered_at_idx'),
        ),
        migrations.AddIndex(
            model_name='negotiations',
            index=models.Index(fields=['accepted_at'], name='accepted_at_idx'),
        ),
        migrations.AddIndex(
            model_name='negotiations',
            index=models.Index(fields=['price'], name='price_idx'),
        ),
        migrations.AddIndex(
            model_name='negotiationhistory',
            index=models.Index(fields=['action'], name='action_idx'),
        ),
        migrations.AddIndex(
            model_name='negotiationhistory',
            index=models.Index(fields=['negotiation'], name='nego_idx'),
        ),
        migrations.AddIndex(
            model_name='negotiationhistory',
            index=models.Index(fields=['created_at'], name='idx_date'),
        ),
    ]
