# Generated by Django 6.0.2 on 2026-03-29 20:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_endorsements'),
        ('users', '0003_alter_providerskill_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='endorsements',
            name='chats_endor_endorem_a45846_idx',
        ),
        migrations.RenameField(
            model_name='endorsements',
            old_name='endorement_id',
            new_name='endorsement_id',
        ),
        migrations.AddIndex(
            model_name='endorsements',
            index=models.Index(fields=['endorsement_id'], name='chats_endor_endorse_6fb2ca_idx'),
        ),
    ]
