# Generated by Django 6.0.5 on 2026-08-06 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_remove_endorsements_unique_sender'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='endorsements',
            name='chats_endor_reason_4820fb_idx',
        ),
        migrations.RenameField(
            model_name='endorsements',
            old_name='reason',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='endorsements',
            name='is_hidden',
        ),
    ]
