# Generated by Django 6.0.2 on 2026-05-13 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_support_room_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='participant_two',
            field=models.ForeignKey(help_text='Second participant in the conversation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_participant_two', to=settings.AUTH_USER_MODEL),
        ),
    ]
