# Generated by Django 6.0.2 on 2026-04-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_remove_endorsements_chats_endor_endorem_a45846_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endorsements',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='endorsements',
            name='is_hidden',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
