# Generated by Django 6.0.5 on 2026-05-30 14:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=200, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='received', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('wallet_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='LockedWallet',
            fields=[
                ('locked_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_released', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('mutable_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='locked', to='bookings.bookings')),
                ('user_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locked_balance', to='wallet.wallet')),
            ],
            options={
                'verbose_name': 'Locked Amount',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('transaction_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdraw')], default=None, max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('idempotency_key', models.UUIDField()),
                ('reference_key', models.CharField(blank=True, max_length=50)),
                ('transfer_code', models.CharField(max_length=50, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('reasons', models.TextField(null=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_transactions', to='wallet.wallet')),
            ],
            options={
                'verbose_name': 'Wallet Transaction',
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('bank_account_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('account_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=10)),
                ('bank_code', models.CharField(max_length=10)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_id', models.CharField(max_length=255, null=True)),
                ('recipient_code', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'bank account',
                'indexes': [models.Index(fields=['user', 'is_active'], name='wallet_bank_user_id_a69f73_idx')],
                'unique_together': {('user', 'account_number', 'bank_code')},
            },
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['wallet_id'], name='pk_idx'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(fields=('wallet_id', 'user'), name='unique_user_wallet'),
        ),
        migrations.AddIndex(
            model_name='lockedwallet',
            index=models.Index(fields=['is_released'], name='wallet_lock_is_rele_47bbaf_idx'),
        ),
        migrations.AddIndex(
            model_name='lockedwallet',
            index=models.Index(fields=['locked_at'], name='wallet_lock_locked__0d8090_idx'),
        ),
        migrations.AddIndex(
            model_name='lockedwallet',
            index=models.Index(fields=['user_wallet'], name='wallet_lock_user_wa_01f8fa_idx'),
        ),
        migrations.AddIndex(
            model_name='lockedwallet',
            index=models.Index(fields=['amount'], name='wallet_lock_amount_cb41ca_idx'),
        ),
        migrations.AddConstraint(
            model_name='lockedwallet',
            constraint=models.UniqueConstraint(fields=('booking', 'user_wallet'), name='unique_wallet'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['amount'], name='wallet_wall_amount_c65c5a_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['status'], name='wallet_wall_status_66d39d_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['type'], name='wallet_wall_type_12424b_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['idempotency_key'], name='wallet_wall_idempot_442271_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['reference_key'], name='wallet_wall_referen_cc4eeb_idx'),
        ),
    ]
