# Generated by Django 6.0.2 on 2026-04-04 07:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0003_bookings_platform_fee_alter_bookings_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransactions',
            fields=[
                ('transaction_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdraw')], default=None, max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('idempotency_key', models.CharField(blank=True, max_length=20)),
                ('reference_key', models.CharField(blank=True, max_length=20, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('transaction_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'PaymentTransactions',
                'indexes': [models.Index(fields=['amount'], name='wallet_paym_amount_145217_idx'), models.Index(fields=['status'], name='wallet_paym_status_160556_idx'), models.Index(fields=['type'], name='wallet_paym_type_e970d9_idx'), models.Index(fields=['idempotency_key'], name='wallet_paym_idempot_975a2c_idx'), models.Index(fields=['reference_key'], name='wallet_paym_referen_858e61_idx')],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('wallet_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='LockedWallet',
            fields=[
                ('locked_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_released', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('mutable_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='locked', to='bookings.bookings')),
                ('user_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locked_balance', to='wallet.wallet')),
            ],
            options={
                'verbose_name': 'Locked Amount',
            },
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['wallet_id'], name='pk_idx'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(fields=('wallet_id', 'user'), name='unique_user_wallet'),
        ),
        migrations.AddIndex(
            model_name='lockedwallet',
            index=models.Index(fields=['is_released'], name='wallet_lock_is_rele_47bbaf_idx'),
        ),
        migrations.AddIndex(
            model_name='lockedwallet',
            index=models.Index(fields=['locked_at'], name='wallet_lock_locked__0d8090_idx'),
        ),
        migrations.AddIndex(
            model_name='lockedwallet',
            index=models.Index(fields=['user_wallet'], name='wallet_lock_user_wa_01f8fa_idx'),
        ),
        migrations.AddIndex(
            model_name='lockedwallet',
            index=models.Index(fields=['amount'], name='wallet_lock_amount_cb41ca_idx'),
        ),
        migrations.AddConstraint(
            model_name='lockedwallet',
            constraint=models.UniqueConstraint(fields=('booking', 'user_wallet'), name='unique_wallet'),
        ),
    ]
