# Generated by Django 6.0.2 on 2026-03-20 08:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('wallet_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='LockedWallet',
            fields=[
                ('locked_wallet_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locked_wallet', to='users.providermodel')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locked_wallet', to='wallet.wallet')),
            ],
            options={
                'verbose_name': 'locked_wallets',
            },
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['wallet_id'], name='pk_idx'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(fields=('wallet_id', 'user'), name='unique_user_wallet'),
        ),
        migrations.AddIndex(
            model_name='lockedwallet',
            index=models.Index(fields=['locked_wallet_id'], name='locked_wallet_id'),
        ),
        migrations.AddIndex(
            model_name='lockedwallet',
            index=models.Index(fields=['wallet'], name='wallet_idx'),
        ),
        migrations.AddIndex(
            model_name='lockedwallet',
            index=models.Index(fields=['provider'], name='prov_idx'),
        ),
        migrations.AddConstraint(
            model_name='lockedwallet',
            constraint=models.UniqueConstraint(fields=('locked_wallet_id', 'wallet'), name='unique_locked_wallet'),
        ),
        migrations.AddConstraint(
            model_name='lockedwallet',
            constraint=models.UniqueConstraint(fields=('wallet', 'provider'), name='unique_wallet_provider_lock'),
        ),
    ]
