# Generated by Django 5.2.8 on 2026-02-22 22:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_providermodel_is_online'),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='locked_balance',
            new_name='balance',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='main_balance',
        ),
        migrations.CreateModel(
            name='LockedWallet',
            fields=[
                ('locked_wallet_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locked_wallet', to='users.providermodel')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locked_wallet', to='wallet.wallet')),
            ],
            options={
                'verbose_name': 'locked_wallets',
                'indexes': [models.Index(fields=['locked_wallet_id'], name='locked_wallet_id'), models.Index(fields=['wallet'], name='wallet_idx'), models.Index(fields=['provider'], name='prov_idx')],
                'constraints': [models.UniqueConstraint(fields=('locked_wallet_id', 'wallet'), name='unique_locked_wallet'), models.UniqueConstraint(fields=('wallet', 'provider'), name='unique_wallet_provider_lock')],
            },
        ),
    ]
