# Generated by Django 6.0.2 on 2026-04-04 12:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('transaction_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdraw')], default=None, max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('idempotency_key', models.CharField(max_length=20)),
                ('reference_key', models.CharField(blank=True, max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('reasons', models.TextField(null=True)),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'PaymentTransactions',
            },
        ),
        migrations.RemoveIndex(
            model_name='paymenttransactions',
            name='wallet_paym_amount_145217_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymenttransactions',
            name='wallet_paym_status_160556_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymenttransactions',
            name='wallet_paym_type_e970d9_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymenttransactions',
            name='wallet_paym_idempot_975a2c_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymenttransactions',
            name='wallet_paym_referen_858e61_idx',
        ),
        migrations.DeleteModel(
            name='PaymentTransactions',
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_transactions', to='wallet.wallet'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['amount'], name='wallet_wall_amount_c65c5a_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['status'], name='wallet_wall_status_66d39d_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['type'], name='wallet_wall_type_12424b_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['idempotency_key'], name='wallet_wall_idempot_442271_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['reference_key'], name='wallet_wall_referen_cc4eeb_idx'),
        ),
    ]
