# Generated by Django 6.0.5 on 2026-07-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='idempotency_key',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='reference_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
