# Generated by Django 6.0.2 on 2026-04-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_wallettransaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='idempotency_key',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='reference_key',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
