# Generated by Django 6.0.2 on 2026-04-17 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_webhookevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallettransaction',
            options={'verbose_name': 'Wallet Transaction'},
        ),
    ]
