# Generated by Django 6.0.2 on 2026-04-23 18:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_alter_wallettransaction_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('bank_account_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('account_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=10)),
                ('bank_code', models.CharField(max_length=10)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_id', models.CharField(max_length=255, null=True)),
                ('recipient_code', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'bank account',
                'indexes': [models.Index(fields=['user', 'is_active'], name='wallet_bank_user_id_a69f73_idx')],
                'unique_together': {('user', 'account_number', 'bank_code')},
            },
        ),
    ]
