# Generated by Django 6.0.2 on 2026-04-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='transfer_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='idempotency_key',
            field=models.UUIDField(),
        ),
    ]
