# Generated by Django 6.0.2 on 2026-05-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_wallettransaction_transfer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
