# Generated by Django 6.0.5 on 2026-05-30 14:51

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('message', models.TextField(max_length=5000)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_edited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='replies', to='posts.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('post_title', models.CharField(max_length=500, null=True)),
                ('post_content', models.TextField()),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('post_type', models.CharField(choices=[('GENERAL', 'General'), ('SERVICE', 'Service'), ('JOB', 'Job')], default='GENERAL', max_length=200, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_reposted', models.BooleanField(db_index=True, default=False)),
                ('is_remote', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('engagement_count', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='tags', to='users.servicecategory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('like_id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='posts.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='posts.post')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post'),
        ),
        migrations.CreateModel(
            name='PostAttachment',
            fields=[
                ('post_attachment_id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('attachment_type', models.CharField(blank=True, choices=[('VIDEO', 'Video'), ('PHOTO', 'Photo'), ('FILE', 'File')], default=None, max_length=200, null=True)),
                ('attachmentURL', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='posts.comment')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='posts.post')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Repost',
            fields=[
                ('repost_id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('original_post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='repost_records', to='posts.post')),
                ('reposted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reposts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPostInteraction',
            fields=[
                ('interaction_id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('like', 'Like'), ('comment', 'Comment'), ('repost', 'Repost')], default='view', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interactions', to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['post_id'], name='post_id_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_active'], name='active_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_deleted'], name='deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['created_at'], name='date_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_active', 'is_deleted'], name='is_deleted_active_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_published'], name='is_published_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['engagement_count'], name='engagement_count_idx'),
        ),
        migrations.AddIndex(
            model_name='likes',
            index=models.Index(fields=['like_id'], name='like_id_idx'),
        ),
        migrations.AddIndex(
            model_name='likes',
            index=models.Index(fields=['post'], name='post_like_idx'),
        ),
        migrations.AddIndex(
            model_name='likes',
            index=models.Index(fields=['comment'], name='comment-idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent'], name='parent_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created_at'], name='time_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['is_active'], name='is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='postattachment',
            index=models.Index(fields=['post'], name='post_id'),
        ),
        migrations.AddIndex(
            model_name='repost',
            index=models.Index(fields=['original_post'], name='repost_original_post_idx'),
        ),
        migrations.AddIndex(
            model_name='repost',
            index=models.Index(fields=['reposted_by'], name='repost_user_idx'),
        ),
        migrations.AddIndex(
            model_name='repost',
            index=models.Index(fields=['created_at'], name='repost_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='repost',
            constraint=models.UniqueConstraint(fields=('original_post', 'reposted_by'), name='unique_user_post_repost'),
        ),
        migrations.AddIndex(
            model_name='userpostinteraction',
            index=models.Index(fields=['user'], name='interaction_user_idx'),
        ),
        migrations.AddIndex(
            model_name='userpostinteraction',
            index=models.Index(fields=['post'], name='interaction_post_idx'),
        ),
        migrations.AddIndex(
            model_name='userpostinteraction',
            index=models.Index(fields=['user', 'post'], name='interaction_user_post_idx'),
        ),
        migrations.AddIndex(
            model_name='userpostinteraction',
            index=models.Index(fields=['interaction_type'], name='interaction_type_idx'),
        ),
        migrations.AddIndex(
            model_name='userpostinteraction',
            index=models.Index(fields=['created_at'], name='interaction_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='userpostinteraction',
            constraint=models.UniqueConstraint(fields=('user', 'post', 'interaction_type'), name='unique_user_post_interaction'),
        ),
    ]
