# Generated by Django 6.0.5 on 2026-06-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postattachment',
            name='public_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
