# Generated by Django 6.0.2 on 2026-03-26 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='postattachment',
            new_name='post_id',
            old_name='post_idx',
        ),
        migrations.RemoveField(
            model_name='post',
            name='role',
        ),
        migrations.AddField(
            model_name='postattachment',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='posts.comment'),
        ),
    ]
