# Generated by Django 6.0.2 on 2026-03-03 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('users', '0003_alter_category_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttag',
            name='service_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_tag', to='users.category'),
        ),
    ]
