# Generated by Django 5.2.8 on 2026-02-10 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('users', '0004_remove_providerskills_profile_name_contraints_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('CUSTOMER', 'Customer'), ('SERVICE_PROVIDER', 'Service_provider')], help_text='User role when creating the post instance', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='servicetag',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_tag', to='users.category'),
        ),
    ]
