# Generated by Django 6.0.5 on 2026-07-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_postattachment_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='postattachment',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
