# Generated by Django 6.0.2 on 2026-04-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_post_idx_post_id_remove_post_role_and_more'),
        ('users', '0007_alter_category_options_alter_providerskill_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='posttag',
            name='unique_post_tag',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='users.skill'),
        ),
        migrations.DeleteModel(
            name='PostTag',
        ),
    ]
