# Generated by Django 6.0.2 on 2026-03-07 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_parent'),
        ('users', '0004_alter_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts_address', to='users.address'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_title',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
