# Generated by Django 6.0.2 on 2026-05-11 16:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_likes_unique_user_and_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='likes',
            index=models.Index(fields=['comment'], name='comment-idx'),
        ),
    ]
