# Generated by Django 6.0.2 on 2026-05-11 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_likes_comment_idx'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='likes',
            name='unique_user_post_like',
        ),
        migrations.RemoveConstraint(
            model_name='likes',
            name='unique-user-and-comment',
        ),
    ]
