# Generated by Django 6.0.2 on 2026-05-12 10:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_likes_unique_user_post_like_and_more'),
        ('users', '0011_baseprofile_category_interest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Repost',
            fields=[
                ('repost_id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPostInteraction',
            fields=[
                ('interaction_id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('like', 'Like'), ('comment', 'Comment'), ('repost', 'Repost')], default='view', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='engagement_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_published'], name='is_published_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['engagement_count'], name='engagement_count_idx'),
        ),
        migrations.AddField(
            model_name='repost',
            name='original_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repost_records', to='posts.post'),
        ),
        migrations.AddField(
            model_name='repost',
            name='reposted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reposts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpostinteraction',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interactions', to='posts.post'),
        ),
        migrations.AddField(
            model_name='userpostinteraction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='repost',
            index=models.Index(fields=['original_post'], name='repost_original_post_idx'),
        ),
        migrations.AddIndex(
            model_name='repost',
            index=models.Index(fields=['reposted_by'], name='repost_user_idx'),
        ),
        migrations.AddIndex(
            model_name='repost',
            index=models.Index(fields=['created_at'], name='repost_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='repost',
            constraint=models.UniqueConstraint(fields=('original_post', 'reposted_by'), name='unique_user_post_repost'),
        ),
        migrations.AddIndex(
            model_name='userpostinteraction',
            index=models.Index(fields=['user'], name='interaction_user_idx'),
        ),
        migrations.AddIndex(
            model_name='userpostinteraction',
            index=models.Index(fields=['post'], name='interaction_post_idx'),
        ),
        migrations.AddIndex(
            model_name='userpostinteraction',
            index=models.Index(fields=['user', 'post'], name='interaction_user_post_idx'),
        ),
        migrations.AddIndex(
            model_name='userpostinteraction',
            index=models.Index(fields=['interaction_type'], name='interaction_type_idx'),
        ),
        migrations.AddIndex(
            model_name='userpostinteraction',
            index=models.Index(fields=['created_at'], name='interaction_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='userpostinteraction',
            constraint=models.UniqueConstraint(fields=('user', 'post', 'interaction_type'), name='unique_user_post_interaction'),
        ),
    ]
