# Generated by Django 6.0.2 on 2026-05-13 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_repost_userpostinteraction_post_engagement_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='post',
            name='repost_quote',
        ),
        migrations.RemoveField(
            model_name='post',
            name='reposted_at',
        ),
        migrations.AlterField(
            model_name='repost',
            name='original_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='repost_records', to='posts.post'),
        ),
    ]
