# Generated by Django 6.0.5 on 2026-07-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0002_alter_supportmessage_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
