# Generated by Django 6.0.5 on 2026-07-16 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0003_support_closed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportconversation',
            name='support',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='custom_admin.support'),
        ),
    ]
