# Generated by Django 6.0.5 on 2026-07-31 18:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0004_alter_supportconversation_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationCategory',
            fields=[
                ('category_id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=266, unique=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpenApplications',
            fields=[
                ('application_id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(db_index=True, max_length=266)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, db_index=True, max_length=500, null=True)),
                ('is_remote', models.BooleanField(default=None)),
                ('job_type', models.CharField(default=None, max_length=50)),
                ('company_name', models.CharField(max_length=266)),
                ('job_link', models.URLField(blank=True)),
                ('min_charge', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('max_charge', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upadted_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='custom_admin.applicationcategory')),
            ],
        ),
    ]
